version: "3.9"
services:
    frontend:
        stdin_open: true
        tty: true
        build:
            context: ./client
            dockerfile: dockerfile.dev
            args:
                - REACT_APP_API_URL=http://127.0.0.1:8080
        volumes:
            - ./client/src:/app/src
        command: npm start
        ports:
            - 3000:3000
        networks:
            - qc-app-dev

    backend:
        stdin_open: true
        tty: true
        build:
            context: ./server
            dockerfile: dockerfile.dev
        volumes:
            - ./server/src:/app/src
        command: npm run dev
        networks:
            - qc-app-dev
    dbmate:
        networks:
            - qc-app-dev
    database:
        networks:
            - qc-app-dev
networks:
    qc-app-dev:
        driver: bridge
