version: "3.9"
services:
    frontend:
        build:
            context: ./client
            dockerfile: dockerfile.prod
        ports:
            - 80:80
            - 443:443
        networks:
            - qc-app-prod
    backend:
        build:
            context: ./server
            dockerfile: dockerfile.prod
        command: npm start
        networks:
            - qc-app-prod
    dbmate:
        networks:
            - qc-app-prod
    database:
        networks:
            - qc-app-prod
networks:
    qc-app-prod:
        driver: bridge
