FROM node:lts-alpine as dev

WORKDIR /app
COPY package*.json ./
RUN npm install -g nodemon
RUN npm install
COPY . .

FROM node:lts-alpine as prod
WORKDIR /app
COPY package*.json ./
ENV NODE_ENV production
RUN npm i --only=production
COPY . .
EXPOSE 8080